apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mackllc
  namespace: argocd
spec:
  description: Mackllc microservices project

  sourceRepos:
    - "https://github.com/your-github-username/gitops.git"

  destinations:
    - server: https://kubernetes.default.svc
      namespace: dev
    - server: https://kubernetes.default.svc
      namespace: qa
    - server: https://kubernetes.default.svc
      namespace: prod

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
