apiVersion: v2
name: mackllc-service
description: Common Helm chart for Mackllc microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - mackllc
  - microservice
  - java
  - spring-boot
maintainers:
  - name: Mackllc DevOps Team
    email: devops@mackllc.com