apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mackllc-ui-qa
  namespace: argocd
  labels:
    env: qa
    app: mackllc-ui
    managed-by: terraform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mackllc

  source:
    repoURL: https://github.com/Alexatlanta1981/gitops.git
    targetRevision: HEAD
    path: helm-charts
    helm:
      valueFiles:
        - ../envs/qa/values-mackllc-ui.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: qa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10